# use ubuntu linux.
os: linux
dist: trusty

# run in container.
sudo: false

# use nodejs environment.
language: node_js
node_js: stable

# install stable chrome and firefox.
addons:
  chrome: stable
  firefox: latest
  sauce_connect: false

# run npm install and install:bower.
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - npm install
  - npm run install:bower

# run npm build and test.
script:
  - npm run build
  - npm run test
